### PR TITLE
Add Cookie to hide "Take Picture" and simple login

### LINKED ISSUE #8: gallery standalone
Make gallery a own page without button to close and without ability to take pictures.

Idea: Move current index.php e.g. to /photobooth (other recommendations welcome, maybe /takepic or /capture)

Other ways possible too (using a cookie?).

### PR DESCRIPTION
**Pull request by F4bsi**
Hey,

here is my Code to be able to only show the gallery to guest users ( resolves #8  ) . I also had a simple login for the simple admin site is used to set the cookie on the device that needs it. Because I think it would be nice to have, I also included it here. If you don't want to use it I can remove it.

It works by setting a cookie via the admin panel. If it is enabled, only devices with the cookie set are able to see the normal start screen. Other devices (normally users who want do download) jump directly into the gallery.

I tried to adapt my old code to all the things that have been changed since back than and also tried to make it a little cleaner, but I didn't had the time to check if everything is working so please be cautious 😉 . I'm quite sure that I forgot something or maybe have some kind of error somewhere.

I hope I find some time in the next few days to finish this properly. I opened my branch to be writable by you, so you should be able to add new commits too.

Thank you for all your work! 👍

### CODE REVIEW

**Comment by andi34** [comment]
Thanks a lot :) I'll take a closer look later if I find enough time, else on weekend I'll have some time :)

**Comment by andi34** [comment]
Thanks a lot @F4bsi ! I've no write access on your fork.
To start with i did:
squash first 3 commits as they belong together, also removed unused config changes (added to the 2nd commit)
https://github.com/andi34/photobooth/commit/3417fd9e3ac48e592dd3a43fdcab72a1905d2025

On the admin page & login change i added the config i removed previously (belongs here), also reverted the formatting changes in admin/index.php to make the changes understandable if you check the commit .
https://github.com/andi34/photobooth/commit/3d8e81e971e58cdea75ba35fb23507a286577222

From what i see what's to do:
add changed config to language files. You've them translated already?

What could be done (better for commit history):
Parts from disable gallery of commit 2 could be moved into commit 1 to make the login option it's own commit.
My question on this: how to set the cookie properly without the login option?

Just out of time for today, hope i find more time this weekend

**Comment by andi34** [comment]
Found one issue: cookie_isset does not work from admin panel, option does not get saved. Any idea why?

**Comment by andi34** [comment]
I guess cookie_isset must be true/false value and everything else need to be set depending on true/false on this via admin.php maybe

**Comment by andi34** [comment]
moved to WIP branch for now https://github.com/andi34/photobooth/commits/WIP

**Comment by andi34** [comment]
@F4bsi your still around and working on it?

**Comment by F4bsi** [comment]
Sorry, I don't have much time right now :(
I should have some time to look into it on friday

**Comment by andi34** [comment]
Don't worry, only wasn't sure if your still around.
Take the time you need :)

**Pull request closed without merging**
