### PR TITLE
Feature/ubuntu image

### PR DESCRIPTION
**Pull request by Metropo**
#### Prerequisites checklist

- [x] I have read the [contributing guidelines](https://github.com/andi34/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)
- [ ] Documentation update
- [ ] Bug fix
- [X] New feature
- [ ] Other, please explain:

#### What changes did you make? (Give an overview)

I created a github action to automatically create a ubuntu live cd (iso) with photobooth preinstalled.
this allows for easy and quick setup of a clean test environment. You can boot it in virtual-box or on any x64
PC from a USB-drive.

There is one issue remaining in the automisation. I was not able to deliver the ISO as artifact in the action.
For now i let github upload the image to a hosting service via SFTP. [(http://beta.photobooth.metropo.de/photobooth.iso.gz)](http://beta.photobooth.metropo.de/photobooth.iso.gz)

Please check if this feature is relevant to you or other users. I personally find it helpful.

Further improvements (autostart of the webbrowser in fullscreen) are on my list ;)

#### Is there anything you'd like reviewers to focus on?

Not really. Nothing in the actual application changed ;)

### CODE REVIEW

**Comment by andi34** [comment]
Hey and thanks @Metropo !
The artifact is visible here: https://github.com/Metropo/photobooth/actions/runs/877595951#artifacts

Download seems to work too, but takes some time.

I find it quite useful to get an iso and a good idea in general!
Most people will use Photobooth on a raspberry pi, maybe there's a solution to generate a iso for the Pi too?

In general I'd only provide a iso if a new release is out, but one limitation to think about: The artifact on GitHub action is only available for some time.

**Comment by Metropo** [comment]
Hi @andi34 
glad that you like the idea.

The artifact behaviour seems not to be too reliable. I was able to download the last one as well, but during my testing (before i added sftp upload) i got some github server side error while trying to download. 

I was thinking of a raspberry pi image as well, should be possible in general i guess, but i did not dig into this topic yet.
On fist glance this seems to be a possible way: [https://geoffhudik.com/tech/2020/05/15/using-pi-gen-to-build-a-custom-raspbian-lite-image/](https://geoffhudik.com/tech/2020/05/15/using-pi-gen-to-build-a-custom-raspbian-lite-image/)

**Comment by andi34** [comment]
Hey @Metropo !
FYI:
I've added the silent installation commit already to the dev branch and changed some default settings :)

**Comment by andi34** [comment]
Hey @Metropo! Do you like to rebase your changes for latest dev branch?
Did you had time to look at a solution to build an image for the raspberry pi?

**Comment by Metropo** [comment]
Hey @andi34, unfortunatly i had to postpone this issue for a while due to a lack of time, but since i recently needed my fotobox again i startet again to work on the issues. I createt a second temporary branch to test and rebase. Ubuntu is working again and the raspberry is on its way. I managed to build a "clean" raspbian without installing yet. So the next step is to call the install script.
And after this i am plannig to rewrite the git history in a clean and understandable way and update this pull request. Unfortunatly working with actions gets messy quick, because every test has to be commited.
Here is my current experimental stage:
https://github.com/Metropo/photobooth/tree/image_builder

**Comment by Metropo** [comment]
Good morning @andi34 ,
I should have both images working with minimal changes on the rest of the repository. Please have a look at the changes and feel free to comment.
I needed to disable the cups remote default setting in the install script because that step fails in both image building processes. It seems that it can't be called in the chroot environment used to preconfigure the images.
I was thinking about another improvement for the install-raspbian.sh silent install where more options can be passed to the script, but so far i did not have a clear picture on how this should work. Maybe thru environment variables like:
```
export ENABLE_CUPS_REMOTE=false
./install-raspbian.sh apache silent
```
For the raspbian implementation i had a look at https://github.com/hyperion-project/HyperBian. They seem to do a fairly similar thing and it was a great headstart.

I am looking forward on your comments, best regard
Christian

**Comment by andi34** [comment]
Wow, great! Thanks a lot! I'll merge this since actions can't be tested without 🙂

I've got on my To-Do-List to add some parts of the installer inside the gphoto directory to the main installer. This would install python3 and all other requirements for a preview via gphoto2. The Ubuntu config will need to be adjusted after that.

And sure, for the installer we could think about adding an optional entry to pass a config file to the installer.

**Comment by andi34** [comment]
Maybe we need to adjust the pi installation, since it's expecting user `pi` with group `pi` on some parts. This is also a problem currently, since on latest Pi OS the user pi was removed by default

https://github.com/andi34/photobooth/blob/8f161622f9e9835354cfcc1023960ae6fc35a968/install-raspbian.sh#L439-L447

You've got an idea how we could handle this a little better?

**Comment by Metropo** [comment]
Thanks for the merge ;)
finally after nearly a year i got the solution cleaned up 🥳 
yes, i had issues there as well with the installer. I wanted to create a user called phtobooth by default, but that interferes with the new piviz first start wizzard. But to be fair i have not much experiance with the photobooth on the raspberry since my box uses an x64 system ;) But of cause i can try to support here ;) Today i also joined the telegram group

**Pull request merged**
