### PR TITLE
Print optimizations and new auto print feature

### PR DESCRIPTION
**Pull request by andi34**
#### Prerequisites checklist

- [X] I have read the [contributing guidelines](https://github.com/andi34/photobooth/blob/dev/CONTRIBUTING.md).

#### What is the purpose of this pull request? (put an "x" next to an item)

- [X] New feature
- [X] Other, please explain: *see below*

#### What changes did you make? (Give an overview)

**Auto print function**
inspired by implementation from alzo425: https://github.com/alzo425/photobooth/commit/90099f17faa16ac4b4b3dd28a0ef7403dc2e29d6
- Slight adjustments for latest Photobooth, removed unneeded code changes

**New options**
- allow to delay auto print
- allow to adjust time "Started printing! Please wait..." is visible
- allow to trigger print via defined key
- check if we're already printing to avoid double printing
- options to show the print button independent

### CODE REVIEW

**Comment by lagrandeours** [comment]
it s very good option if it s possible to add a delay of 3/5 seconds to let people take picture again if the picture is not good

**Comment by andi34** [comment]
In that case better don't enable the option and use the print button.

**Comment by andi34** [comment]
Need to add missing strings, will force push in the evening.

**Comment by andi34** [comment]
On my To-Do-List as further improvements
- [ ] print-counter
- [ ] allow printing 2 pictures or more

**Pull request merged**
