### PR TITLE
added collage function

### PR DESCRIPTION
**Pull request by flighter18**
now you have an additional button on the webinterface. if you push this button, the camera will take 4 pictures and merge them to a collage.

### CODE REVIEW

**Comment by andi34** [comment]
Thx, I'll check next days :) :+1:

**Comment by firesta666** [comment]
And if you write the php for the 4 pictures, maybe you can add that if the basic settings are come back automaticaly to 1 picture without collage, if the user don't touch a new picture or after X seconds (value from the config / webinterface).

other idea: in the homescreen can choose: 

1 picture
4 pictures as collage
gallery
email
etc.

**Comment by flighter18** [comment]
It is allready implemented. 
From the homescreen you can choose between 1 picture or 4 picture. Those are 2 different buttons.

**Comment by firesta666** [comment]
Oh ok, sorry for the question. 

How i can find it, to implement it on 1.8 ?

**Comment by andi34** [comment]
I've to separate the changes made. It's mixed with changes from my branch which have it's own commits.
Celebrating my birthday today with friends, maybe in the morning I can split the changes and push to my GitHub.
Until that you can clone from flighter or add his fork as remote and switch to it.

```
git remote add flighter18 https://github.com/flighter18/photobooth
git fetch flighter18
git checkout flighter18/master
```

**Comment by andi34** [comment]
https://github.com/andi34/photobooth/commit/c436d6b010319f2aba58ca0cd635b35edf59302f

hope i've not overseen something

**Comment by andi34** [comment]
Not tested. Quickly seperated the changes and pushed.
If someone finds anything wrong let me know.

**Comment by flighter18** [comment]
happy birthday @andi34 :)

**Comment by andi34** [comment]
WIP in dev branch. Will be ready soon.

**Pull request closed without merging**
