### PR TITLE
fix typo in FAQ-Code

### PR DESCRIPTION
**Pull request by danielh84**
#### What is the purpose of this pull request? (put an "x" next to an item)

- [x] Documentation update

### CODE REVIEW

**Comment by andi34** [comment]
Hey and thanks for the finding!  It needs to be adjusted in the md5, else it's removed again once you run `yarn build`

**Review by andi34 — CHANGES_REQUESTED** [review]
Changes need to be done to `faq/faq.md5`, after that run `yarn build` and commit your changes. 

https://github.com/andi34/photobooth/blob/dev/CONTRIBUTING.md#committing-and-pushing-changes

**Comment by danielh84** [comment]
i did `yarn build:faq` but there are no other changes instead of my changes in the faq.md file

**Comment by joiyco** [comment]
Could you add this to the PR.
For persistent on Startup add the following lines to before exit 0
/etc/rc.local:
modprobe v4l2loopback exclusive_caps=1 card_label="GPhoto2 Webcam"
rmmod bcm2835-isp

**Comment by andi34** [comment]
@danielh84 you only need to edit the faq.md, yarn build will create the updated html (I'll remove the html from git and add it to gitignore once this PR is merged, or you could add this change here too)

**Review by andi34 — APPROVED** [review]
Thanks

**Pull request merged**
